### ISSUE TITLE
Canceling "clear" - unexpectedly clears the document anyway

### ISSUE THREAD

**Issue by mountainash** [nico-martin/markdown-editor#11]
It seems that there's a "safari only" feature (doesn't show in Chrome) that shows a "clear"/eraser button at the top of the screen - when clicked a prompt is shown with "Are you sure you want to close this file? Unsaved changes will be lost." [ok] or [cancel].

You'd expect that "cancel" would dismiss the prompt and allow you to keep editing your existing document in the background/behind the prompt.... but it doesn't, "cancel" does the same as "ok" and closes the doc showing the homescreen again. 

- [x] change cancel to just dismiss the prompt dialog returning the user to their current doc

Version: v3.1.16
Tested at: https://md.nico.dev/

**Comment by nico-martin** [comment]
Hi @mountainash 
Thanks for pointing that out!
I just fixed it with v3.1.17
